version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - proj_network

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://kafka-broker:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka-broker:9092, PLAINTEXT://kafka-broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - proj_network

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka-broker:29092"
    depends_on:
      - broker
    networks:
      - proj_network

  jobmanager:
    image: flink:latest
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./flink/jobs:/opt/flink/jobs
      - ./flink/Results/Query1/Query1_1_day:/opt/flink/Results/Query1/Query1_1_day
      - ./flink/Results/Query1/Query1_3_days:/opt/flink/Results/Query1/Query1_3_days
      - ./flink/Results/Query1/Query1_all_days:/opt/flink/Results/Query1/Query1_all_days
      - ./flink/Results/Query2/Query2_1_day:/opt/flink/Results/Query2/Query2_1_day
      - ./flink/Results/Query2/Query2_3_days:/opt/flink/Results/Query2/Query2_3_days
      - ./flink/Results/Query2/Query2_all_days:/opt/flink/Results/Query2/Query2_all_days
      - ./flink/Results/Query3:/opt/flink/Results/Query3
    networks:
      - proj_network

  taskmanager:
    image: flink:latest
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 12
    volumes:
      - ./flink/jobs:/opt/flink/jobs
      - ./flink/Results/Query1/Query1_1_day:/opt/flink/Results/Query1/Query1_1_day
      - ./flink/Results/Query1/Query1_3_days:/opt/flink/Results/Query1/Query1_3_days
      - ./flink/Results/Query1/Query1_all_days:/opt/flink/Results/Query1/Query1_all_days
      - ./flink/Results/Query2/Query2_1_day:/opt/flink/Results/Query2/Query2_1_day
      - ./flink/Results/Query2/Query2_3_days:/opt/flink/Results/Query2/Query2_3_days
      - ./flink/Results/Query2/Query2_all_days:/opt/flink/Results/Query2/Query2_all_days
      - ./flink/Results/Query3:/opt/flink/Results/Query3
    networks:
      - proj_network

networks:
  proj_network:
    driver: bridge
